services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: temporal
      MYSQL_USER: temporal
      MYSQL_PASSWORD: temporal
      MYSQL_DATABASE: temporal
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  temporal:
    image: temporalio/auto-setup:1.21.3
    ports:
      - "7233:7233"
    environment:
      - DB=mysql
      - MYSQL_SEEDS=mysql
      - DB_PORT=3306
      - MYSQL_USER=temporal
      - MYSQL_PWD=temporal
      - LOG_LEVEL=debug
    depends_on:
      - mysql

  temporal-ui:
    image: temporalio/ui:2.17.2
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    command:
      - /usr/local/bin/etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=default=http://0.0.0.0:2380
      - --initial-cluster-state=new
      - --name=default
    ports:
      - "2379:2379"
      - "2380:2380"

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:3.1.0
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8085:8085"

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.4
    command: ["milvus", "run", "standalone"]
    depends_on:
      - etcd
      - minio
      - pulsar
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - PULSAR_ADDRESS=pulsar://pulsar:6650
